### ISSUE TITLE
Error with php 7.4

### ISSUE THREAD

**Issue by binary64** [webimpress/coding-standard#115]
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: bracket_closer in /home/user/.config/composer/vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/WhiteSpace/BraceBlankLineSniff.php on line 46

**Comment by michalbundyra** [comment]
Thanks for reporting, can you provide example file please? Tests are running on php 7.4 without issues so I would need to know what exactly causes that issue. Thanks!

**Comment by binary64** [comment]
```
<?php

namespace ThisIsImportant;

public function a()
{
    $this->results = array_map(
        function ($e) use ($className, $context) {
        },
        $result
    );
}
```

**Comment by binary64** [comment]
Another..

```
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: bracket_closer in /home/user/.config/composer/vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/WhiteSpace/BraceBlankLineSniff.php on line 46 in /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 /home/user/.config/composer/vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/WhiteSpace/BraceBlankLineSniff.php(46): PHP_CodeSniffer\Runner->handleErrors()
#1 /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Files/File.php(496): WebimpressCodingStandard\Sniffs\WhiteSpace\BraceBlankLineSniff->process()
#2 /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Files/LocalFile.php(91): PHP_CodeSniffer\Files\File->process()
#3 /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Fixer.php(174): PHP_CodeSniffer\Files\LocalFile->process()
#4 /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(49): PHP_C in /home/user/.config/composer/vendor/squizlabs/php_codesniffer/src/Runner.php on line 606
```

for this code:

```
<?php

if(isset($_POST))
{
}
else
{ ?>
<? }
?>
```

**Comment by michalbundyra** [comment]
@binary64 
> Undefined index: parenthesis_closer in /home/user/.config/composer/vendor/pheromone/phpcs-security-audit/Security/Sniffs/BadFunctions/CallbackFunctionsSniff.php on line 34 

sorry, but it looks like issue in another library, not here.

I've tried use both files you provided - so created new file with the content you have given and run:

```console
 ./vendor/bin/phpcs --sniffs=WebimpressCodingStandard.WhiteSpace.BraceBlankLine ./file.php
```

and for both I am getting no issues:

```console
. 1 / 1 (100%)
```

It looks like some other sniff is mixing up something with your files.

Could you please recheck this and provide me a valid test case if it is still an issue? Thanks!
